# Artificial Neural Network

## Single Layer Neural Network

### Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.16.1'

## Data Preprocessing


### Importing the dataset

In [3]:
dataset = pd.read_csv(r"C:\Users\sakshi\OneDrive\Desktop\FSDS course NIT\Artificial Intelligence\Deep Learning\3rd, 4th - ANN THEORY, Installation\Practicle - CPU\ANN_ 1st\Churn_Modelling.csv")

In [4]:
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age   
0          1    15634602  Hargrave          619    France  Female   42  \
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember   
0       2       0.00              1          1               1  \
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [5]:
X = dataset.iloc[:,3:-1].values
y = dataset.iloc[:,-1].values

In [6]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [7]:
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

### Encoding categorical data

In [35]:
#Encoding categorical columns by using label encoder
from sklearn.preprocessing import LabelEncoder
le =  LabelEncoder()
X[:,2] = le.fit_transform(X[:,2])

In [36]:
X

array([[ 0.99720391, -0.57873591,  0.        , ...,  0.64609167,
         0.97024255,  0.02188649],
       [-1.00280393, -0.57873591,  1.        , ..., -1.54776799,
         0.97024255,  0.21653375],
       [ 0.99720391, -0.57873591,  0.        , ...,  0.64609167,
        -1.03067011,  0.2406869 ],
       ...,
       [ 0.99720391, -0.57873591,  0.        , ..., -1.54776799,
         0.97024255, -1.00864308],
       [-1.00280393,  1.72790383,  0.        , ...,  0.64609167,
        -1.03067011, -0.12523071],
       [ 0.99720391, -0.57873591,  0.        , ...,  0.64609167,
        -1.03067011, -1.07636976]])

In [37]:
# One Hot Encoding the "Geography" column
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [38]:
X

array([[ 1.        ,  0.        ,  0.99720391, ...,  0.64609167,
         0.97024255,  0.02188649],
       [ 1.        ,  0.        , -1.00280393, ..., -1.54776799,
         0.97024255,  0.21653375],
       [ 1.        ,  0.        ,  0.99720391, ...,  0.64609167,
        -1.03067011,  0.2406869 ],
       ...,
       [ 1.        ,  0.        ,  0.99720391, ..., -1.54776799,
         0.97024255, -1.00864308],
       [ 0.        ,  1.        , -1.00280393, ...,  0.64609167,
        -1.03067011, -0.12523071],
       [ 1.        ,  0.        ,  0.99720391, ...,  0.64609167,
        -1.03067011, -1.07636976]])

### Feature Scaling

In [39]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)

In [40]:
X

array([[ 0.57873591, -0.57873591,  0.99720391, ...,  0.64609167,
         0.97024255,  0.02188649],
       [ 0.57873591, -0.57873591, -1.00280393, ..., -1.54776799,
         0.97024255,  0.21653375],
       [ 0.57873591, -0.57873591,  0.99720391, ...,  0.64609167,
        -1.03067011,  0.2406869 ],
       ...,
       [ 0.57873591, -0.57873591,  0.99720391, ..., -1.54776799,
         0.97024255, -1.00864308],
       [-1.72790383,  1.72790383, -1.00280393, ...,  0.64609167,
        -1.03067011, -0.12523071],
       [ 0.57873591, -0.57873591,  0.99720391, ...,  0.64609167,
        -1.03067011, -1.07636976]])

## Splitting the dataset into the training set and test set

In [41]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [42]:
print(X_train.shape)

(8000, 13)


In [43]:
print(y_train.shape)

(8000,)


In [44]:
y_train

array([0, 0, 0, ..., 0, 0, 1], dtype=int64)

## Building the ANN

### Initializing  the ANN

In [45]:
ann = tf.keras.models.Sequential()

### Adding the input layer

In [46]:
ann.add(tf.keras.layers.Dense(units= 12, activation = 'relu'))

### Adding the hidden layer

In [47]:
ann.add(tf.keras.layers.Dense(units = 8, activation = 'relu'))

### Adding the output layer

In [48]:
ann.add(tf.keras.layers.Dense(units = 1, activation = 'sigmoid'))

## Training the ANN

### Compiling the ANN

In [62]:
ann.compile(optimizer='Adam',loss = 'binary_crossentropy',metrics=['accuracy'])

### Training the ANN on the Training set

In [63]:
history= ann.fit(X_train, y_train, batch_size = 32, epochs = 50)

Epoch 1/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8690 - loss: 0.3274
Epoch 2/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8555 - loss: 0.3401
Epoch 3/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8678 - loss: 0.3208
Epoch 4/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8606 - loss: 0.3348
Epoch 5/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8733 - loss: 0.3172
Epoch 6/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8660 - loss: 0.3190
Epoch 7/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8603 - loss: 0.3356
Epoch 8/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8654 - loss: 0.3251
Epoch 9/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8623 - loss: 0.3312
Epoch 10/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8658 - loss: 0.3323
Epoch 11/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8667 - loss: 0.3220
Epoch 12/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

## Making the predictions and evaluating the model

### Predicting the Test set results

In [34]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

In [33]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1499   96]
 [ 199  206]]
